### ISSUE TITLE
Exporting document as HTML like

### ISSUE THREAD

**Issue by dardinier** [typeskill/typer#90]
Hi @jsamr, this lib looks incredible.

Is there a way to export the created document as HTML content or something readable by other thing than the `Print` component ?

Because I would like to use it to create articles which will be saved in a database as HTML and then show these articles in an other component or even in a web page.

**Comment by jsamr** [comment]
@dardinier This feature hasn't been implemented yet but it should be pretty straightforward to do (document → HTML). However, the other way (HTML → document) is more complex because, of course, HTML is way richer than formatted text. I am working hard on other projects right now and I don't have much time to dedicate to typeskill, but this project will receive more care in the future, that I can promise! I'm very open to a PR if you're willing to put the effort.

**Comment by dardinier** [comment]
Thank you for your answer !

I'll try to take a look for this feature then ! :wink:
